steps:
  # Step 1: Run unit tests (install dependencies and then run tests)
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install -r requirements.txt && python -m unittest test_main.py'

  # Step 2: Deploy to Google Cloud Functions (Gen 2)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'calculator-service-aula5'
      - '--gen2'
      - '--runtime=python311'
      - '--trigger-http'
      - '--no-allow-unauthenticated'
      - '--entry-point=calculate'
      - '--region=us-central1'
      - '--service-account=calculator-service-sa@andresousa-puc.iam.gserviceaccount.com'
      - '--set-secrets=CALCULATOR_SECRET=calculator-secret:latest'
